apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: inhotel-agent-app
type: Opaque
stringData:
  # GCP Configuration
  GCP_PROJECT_ID: "REPLACE_ME"
  GCP_LOCATION_ID: "REPLACE_ME"
  KMS_KEY_RING_ID: "REPLACE_ME"
  KMS_KEY_ID: "REPLACE_ME"
  
  # Service Secrets
  IOS_CRYPTO_SECRET: "REPLACE_ME"
  GATEWAY_SECRET: "REPLACE_ME"
  MONGO_PASSWORD: "REPLACE_ME"
  MONGO_INITDB_ROOT_USERNAME: "azam"
  
  # Database URLs (Added)
  MONGO_URI: "REPLACE_ME"
  CONTEXT_DATABASE_URL: "REPLACE_ME"
  CONTROL_DATABASE_URL: "REPLACE_ME"
  EVENT_DATABASE_URL: "REPLACE_ME"

  # Application Secrets
  ENGINEERING_ACCOUNT_BUILDABLE_ID: "REPLACE_ME"
  BUILDABLE_SECRET: "REPLACE_ME"
  CORE_USER_SECRET: "REPLACE_ME"
  DEFAULT_LIVE_ACCESS_KEY: "REPLACE_ME"
  DEFAULT_TEST_ACCESS_KEY: "REPLACE_ME"
  DEVELOPER_ACCOUNT_ACCESS_KEY: "REPLACE_ME"
  DEVELOPER_ACCOUNT_ID: "REPLACE_ME"
  EVENT_ACCESS_PASSWORD: "REPLACE_ME"
  JWT_SECRET: "REPLACE_ME"
  
  # New variables added
  QA_ACCOUNT_BUILDABLE_ID: "REPLACE_ME"
  DEMO_ACCOUNT_EVENT_ACCESS_KEY: "REPLACE_ME"
  QA_ACCOUNT_EVENT_ACCESS_KEY: "REPLACE_ME"